const https = require('https');

const ZOHO_CLIENT_ID = '1000.SKE0C4R2XJQPLS0QECU8O7AN5VX91J';
const ZOHO_CLIENT_SECRET = 'e75f5f8803daa8faa0dafe8ec70f72c94e546b1a6c';
const ZOHO_REDIRECT_URI = 'https://fatemi-pam.netlify.app/';
const ZOHO_TOKEN_URL = 'https://accounts.zoho.com/oauth/v2/token';
const ZOHO_API_BASE = 'https://projectsapi.zoho.com/restapi/v2';

function makeRequest(url, method = 'GET', headers = {}, body = null) {
  return new Promise((resolve, reject) => {
      const options = new URL(url);
          const req = https.request({
                hostname: options.hostname,
                      path: options.pathname + options.search,
                            method,
                                  headers
                                      }, (res) => {
                                            let data = '';
                                                  res.on('data', chunk => data += chunk);
                                                        res.on('end', () => {
                                                                try {
                                                                          resolve({ status: res.statusCode, data: JSON.parse(data) });
                                                                                  } catch {
                                                                                            resolve({ status: res.statusCode, data });
                                                                                                    }
                                                                                                          });
                                                                                                              });
                                                                                                              
                                                                                                                  req.on('error', reject);
                                                                                                                      if (body) req.write(body);
                                                                                                                          req.end();
                                                                                                                            });
                                                                                                                            }
                                                                                                                            
                                                                                                                            exports.handler = async (event) => {
                                                                                                                              try {
                                                                                                                                  const { action, code, token } = JSON.parse(event.body);
                                                                                                                                  
                                                                                                                                      if (action === 'exchange-code') {
                                                                                                                                            // Exchange auth code for access token
                                                                                                                                                  const params = new URLSearchParams({
                                                                                                                                                          code,
                                                                                                                                                                  client_id: ZOHO_CLIENT_ID,
                                                                                                                                                                          client_secret: ZOHO_CLIENT_SECRET,
                                                                                                                                                                                  redirect_uri: ZOHO_REDIRECT_URI,
                                                                                                                                                                                          grant_type: 'authorization_code'
                                                                                                                                                                                                });
                                                                                                                                                                                                
                                                                                                                                                                                                      const tokenRes = await makeRequest(ZOHO_TOKEN_URL, 'POST', {
                                                                                                                                                                                                              'Content-Type': 'application/x-www-form-urlencoded'
                                                                                                                                                                                                                    }, params.toString());
                                                                                                                                                                                                                    
                                                                                                                                                                                                                          if (tokenRes.data.access_token) {
                                                                                                                                                                                                                                  return {
                                                                                                                                                                                                                                            statusCode: 200,
                                                                                                                                                                                                                                                      body: JSON.stringify({ access_token: tokenRes.data.access_token })
                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                            return { statusCode: 400, body: JSON.stringify({ error: 'Token exchange failed' }) };
                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                          if (action === 'fetch-tasks' && token) {
                                                                                                                                                                                                                                                                                                // Fetch projects
                                                                                                                                                                                                                                                                                                      const projectsRes = await makeRequest(`${ZOHO_API_BASE}/projects`, 'GET', {
                                                                                                                                                                                                                                                                                                              'Authorization': `Zoho-oauthtoken ${token}`
                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                          let paccseProjectId = null;
                                                                                                                                                                                                                                                                                                                                if (projectsRes.data.projects) {
                                                                                                                                                                                                                                                                                                                                        const paccseProj = projectsRes.data.projects.find(p => p.name && p.name.includes('PACCSE'));
                                                                                                                                                                                                                                                                                                                                                if (paccseProj) paccseProjectId = paccseProj.id;
                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                            if (!paccseProjectId) {
                                                                                                                                                                                                                                                                                                                                                                    return { statusCode: 200, body: JSON.stringify({ tasks: [] }) };
                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                // Fetch tasks from PACCSE project
                                                                                                                                                                                                                                                                                                                                                                                      const tasksRes = await makeRequest(`${ZOHO_API_BASE}/projects/${paccseProjectId}/tasks`, 'GET', {
                                                                                                                                                                                                                                                                                                                                                                                              'Authorization': `Zoho-oauthtoken ${token}`
                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                          return {
                                                                                                                                                                                                                                                                                                                                                                                                                  statusCode: 200,
                                                                                                                                                                                                                                                                                                                                                                                                                          body: JSON.stringify(tasksRes.data)
                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                        return { statusCode: 400, body: JSON.stringify({ error: 'Invalid action' }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                              return { statusCode: 500, body: JSON.stringify({ error: error.message }) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                };
